# Глубокие нейросети в компьютерном зрении. Дополнительная профессиональная программа профессиональной переподготовки.
# Модуль 1.  Программирование компьютерного зрения на языке Python.

## Лабораторная работа №1 "Обработка многомерных массивов с использованием  библиотеки NumPy"

Выполнил студент Мовенко К.М. группы ИС/б-21-2-о.

### Интерпретатор IPython и оболочка Jupyter

Интерпретатор **IPython** позволяет работать с кодом на языке Python в интерактивном режиме. Среди функций, которые предоставляет IPython, наиболее интересны следующие:
	динамический анализ объектов;
	доступ к оболочке системы через командную строку;
	прямая поддержка профилирования;
	работа с отладочными средствами.
IPython является частью более крупного проекта под названием Jupyter, предоставляющего возможность интерактивной работы через интернет-браузер. 

**Jupyter** - веб-оболочка для интерпретатора IPython, позволяющая объединить код, текст, формулы и диаграммы в единый документ (*блокнот Jupyter*) и распространять их для других пользователей.

Пример работы с разметкой среды Jupyter можно посмотреть в этом блокноте и в [блокноте с разнообразными примерами использования символов и тегов разметки](https://github.com/jupyter/notebook/blob/master/docs/source/examples/Notebook/Working%20With%20Markdown%20Cells.ipynb)

Для быстрого доступа к документации и другой соответствующей информации в IPython используется знак `?`. Например справку по команде `len` можно поучить так:

In [1]:
len?

Такой подход можно применять к любым функциям и методам в IPython.

In [2]:
L = [1,2,3]
L.insert?

#### "Магические" команды IPython
"Магические" команды позволяют организовывать выполнение подпрограмм в среде IPython, а также их профилирование, отладку и другие операции, не связанные непосредственно с языком Python.

Например, команда `%run <скрипт>` запускает в интерактивной оболочке IPython скрипт на Python,
а `%timeit`автоматически определяет время выполнения следующего за ней однострочного оператора. 

Эта команда будет выполнять множественные запуски с целью получения максимально надежных результатов. 

In [3]:
%timeit L = [n ** 2 for n in range(1000)]

86.1 µs ± 18.5 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


Справку по магическим функциям можно получить при помощи знака `?`. Например:

In [4]:
%timeit?

Для доступа к общему описанию доступных «магических» функций введите команду:

In [5]:
%magic

Для быстрого получения простого списка всех доступных «магических» функций:

In [6]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

С помощью «магической» функции %xmode (сокращение от exception mode — режим отображения исключений) мы можем управлять тем, какая информация будет выведена.
Функция %xmode принимает на входе один аргумент, режим, для которого есть три значения: Plain (Простой), Context (По контексту) и Verbose (Расширенный).

#### Отладка и профилирование.

Отладчик в оболочке IPython называется ipdb (сокращение от IPython Debugger — «отладчик IPython»).

Интерфейс для отладки в IPython — «магическая» команда `%debug`. Если ее вызвать после столкновения с исключением, она автоматически откроет интерактивную командную строку откладки в точке возникновения исключения. Командная строка ipdb позволяет изучать текущее состояние стека, доступные переменные и даже выполнять команды Python.
Для подробной информации воспользуйтесь командой help в отладчике или загляните в [онлайн-документацию по ipdb](https://github.com/gotcha/ipdb)

Оболочка IPython предоставляет широкий выбор функциональности для выполнения подобного мониторинга скорости выполнения кода и его профилирования. Для этого применяются следующие "магические команды":

* `%time` — длительность выполнения отдельного оператора;
* `%timeit` — длительность выполнения отдельного оператора при неоднократном повторе, для большей точности;
* `%prun` — выполнение кода с использованием профилировщика;
* `%lprun` — пошаговое выполнение кода с применением профилировщика;
* `%memit` — оценка использования оперативной памяти для отдельного оператора;
* `%mprun` — пошаговое выполнение кода с применением профилировщика памяти.


Пример работы команды `%timeit` рассмотрен выше. Он позволяет оценивать время выполнения однострочных инструкций, выполняя многократный их запуск.

In [7]:
%timeit sum(range(100))

671 ns ± 137 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Если же нужно оценить время, которое затрачивается на выполнение нескольких строк кода, нужно использовать команду с двумя знаками `%` - `%%timeit`:

In [8]:
%%timeit
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

151 ms ± 678 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


Для некоторых фрагментов кода будет полезно оценивать их длительность работы только по одному запуску. Для этого можно применять команду `%time` или `%%time` для многострочного фрагмента:

In [9]:
%%time
    total = 0
    for i in range(1000):
        for j in range(1000):
            total += i * (-1) ** j

CPU times: total: 234 ms
Wall time: 248 ms


Программы состоят из множества отдельных операторов, и иногда оценка времени их выполнения в контексте важнее, чем по отдельности. В языке Python имеется встроенный профилировщик кода (о котором можно прочитать в документации 
языка Python), но оболочка IPython предоставляет намного более удобный способ его использования в виде «магической» функции `%prun`. Для пошагового профилирования может использоваться функция `%lprun`. Аналогично для профилирования объема используемой оперативной памяти могут применяться команды  `%memit` и `%mprun`. Подробную информацию о них можно узнать воспользовавшись справкой по этим командам.

### Основы Python

#### Введение

Python - популярный язык программирования общего назначения, а с помощью нескольких  библиотек numpy, scipy, matplotlib он становится мощной средой для научных вычислений.

Мы ожидаем, что у многих из вас уже есть некоторый опыт работы с Python и numpy; для остальных этот блокнот будет служить как быстрым введением в язык программирования Python, так и введением в использование Python для научных вычислений.

Будут рассмотрены:
* Основы языка Python: основные типы данных (контейнеры: списки, словари, множества, кортежи), функции, классы
* Библиотека Numpy: массивы, индексирование массивов, типы данных, математика массивов, трансляция

#### Основы языка Python

Python - высокоуровневый, динамически типизированный язык программирования. Код на Python часто сравнивают с псевдокодом, поскольку он позволяет вам выражать мощные алгоритмы в нескольких строках кода, оставаясь очень читабельным.

Рассмотрите как в Python выполняют определение и вызов функций, на примере классической рекурсивной функции быстрой сортировки:

In [10]:
# определение функции
def quicksort(arr):                                   # заголовок функции - def имя (входной аргумент):
    if len(arr) <= 1:                                 # условие завершения рекурсии
        return arr                                    # return - оператор, возвращающий результат в точку вызова функции
    pivot = arr[len(arr) // 2]                        # значение серединного эл-та входного списка
    left = [x for x in arr if x < pivot]              # формирование левого подсписка со значениями меньше серединного эл-та
    middle = [x for x in arr if x == pivot]           # формирование среднего подсписка со значениями равными серединному эл-ту
    right = [x for x in arr if x > pivot]             # формирование подсписка со значениями больше серединного эл-та 
    return quicksort(left) + middle + quicksort(right)# рекурсивная сортировка левого и правого подсписков и объединение рез-тов

# вызов функции
print(quicksort([3,6,8,10,1,2,5,7]))

[1, 2, 3, 5, 6, 7, 8, 10]


#### Версия Python

В лабораторных работах рекомендуется использовать дистрибутив Anaconda Python, отличающийся простотой установки. В него входит практически всё необходимое для выполнения лабораторных работ, в том числе:
- интерпретатор IPython; 
- большинство библиотек Python;
- локальный сервер Jupyter Notebook для загрузки и выполнения блокнотов.

Все задания из лабораторных работ протестированы в версии Python 3.6. Предоставляемый код ряда модулей лабораторных работ не поддерживается в версиях выше Python 3.6. 

Вы можете проверить свою версию Python в командной строке, запустив `python -V`.

Если в вашей системе уже была установлена версия выше, чем Python 3.6, то рекомендуется создать отдельную среду для работы с Python 3.6, введя в командном окне conda команду:

conda create --name env-name python=3.6
    
Здесь env-name - название среды, например, python36. Чтобы войти в среду, которая была только что создана, активируйте её:

	conda activate python36

Для выхода из среды python36 выполните команду деактивации

	conda deactivate 

Вы вернетесь к версии Python, которая была ранее установлена в системе. 


#### Основные типы данных

##### Числа

Работа с целыми и вещественными числами выполняется аналогично другим высокоуровневым языкам. Примеры:

In [11]:
!python -V          #проверка версии Пайтон
x = 7
print(x, type(x))   #вывод значения и типа переменной

Python 3.11.4
7 <class 'int'>


In [12]:
print(x + 1)   # Сложение;
print(x - 1)   # Вычитание;
print(x * 2)   # Умножение;
print(x ** 2)  # Возведение в степень;
print(x/2)     # Деление
print(x//2)    # Целочисленное деление
print(x%2)     # Остаток от деления

8
6
14
49
3.5
3
1


In [13]:
x += 1    # x=x+1
print(x)  
x *= 2    # x=x*2
print(x) 

8
16


In [14]:
y = 0.5
print(type(y)) # Печатает "<type 'float'>"
print(y, y + 1, y * 2, y ** 2) 

<class 'float'>
0.5 1.5 1.0 0.25


Обратите внимание: в отличие от многих языков Python не имеет унарных инкрементов (x++) или декрементов (x--).
Python также имеет встроенные типы для работы с длинными целыми чиселами и комплексных числами.

#### Получение ввода от пользователя

Встроенная функция input вводит данные с клавиатуры и всегда возвращает их в виде строки, например:

In [15]:
name = input("Введите Ваше имя?")
name

Введите Ваше имя?Константин


'Константин'

Если Вам необходимо, например, запросить у пользователя целое число, то преобразуйте строку, возращаемую функцией input в число функцией int:

In [16]:
value = int(input('Введите целое число: '))
value

Введите целое число: 20


20

Если строка, переданная int, не может быть преобразована в целое число, то происходит ошибка ValueError.
Для преобразования строк в числа с плавающей точкой используется встроенная функция float.

##### Логические переменные и операции

Python реализует все обычные операции булевой логики. Для обозначения таких операций используются английские слова, а не символы (`&&`, `||` и т. д.).

In [17]:
t, f = True, False # Логические константы
print(type(t))     # Выводит "<type 'bool'>"

<class 'bool'>


Логические операции:

In [18]:
print(t and f) # Логическое И;
print(t or f)  # Логическое ИЛИ;
print(not t)   # Логическое отрицание;
print(t != f)  # Исключающее ИЛИ;

False
True
False
True


##### Строки

Python имеет встроенный строковый тип (класс) str. Сроковая константа заключается в одинарные или двойные кавычки: ‘hellow’, “hellow”. Оператор  “+” позволяет выполнить конкатенацию строк:

In [19]:
hello = 'hellow'   
world = "world"   
print(hello, len(hello))

hellow 6


In [20]:
hw = hello + ' ' + world  # Конкатенация
print(hw)  # Выводит "hello world"

hellow world


Python позволяет сохранять не только строки, но и целые строковые выражения в переменных. Например, можно сохранить в строковой переменной строку, определяющую формат печати переменных:

In [21]:
hw12 = '%s %s %d' % (hello, world, 12)  # строка форматирования в духе функции sprintf языка Си: %s,%d - специкаторы формата
print(hw12)  # выводит "hello world 12"

hellow world 12


Строковые объекты имеют множество полезных методов. Вызов метода выполняется с помощью составного оператора, состоящего из имени объекта, точки и имени метода,  например:

In [22]:
s = "hellow"
print(s.capitalize())  # Преобразование первой буквы в заглавную
print(s.upper())       # Преобразование всех букв строки в заглавные
print(s.rjust(8))      # Выравнивание строки по правому краю поля (длина поля 8 позиций), дополнение пробелами слева
print(s.center(8))     # Центрирование строки, дополнение пробелами
print(s.replace('l', '(ell)'))  # Замена всех экземпляров одной подстроки другой подстрокой
                                # выводит "he(ell)(ell)o"
print('  world '.strip())  # Удаление ведущих и концевых пробелов строки

Hellow
HELLOW
  hellow
 hellow 
he(ell)(ell)ow
world


Cтроки являются неизменяемыми — это означает, что их нельзя модифицировать в программе. Вы можете прочитать отдельные символы в строке, но при попытке присвоить новое значение одному из символов строки будет ошибка TypeError:

In [23]:
s = 'hello'
print(s[0]) # Вывод первого символа строки
s[0] = 'H'  # Попытка записи символа в строку

h


TypeError: 'str' object does not support item assignment

Python предоставляет возможности форматирования выводимых значений с использованием форматных строк (f - строк). 

In [24]:
average = 15.6666
print(f'Cреднее равно {average:.2f}')

Cреднее равно 15.67


Буква f перед открывающей кавычкой строки означает, что это форматная строка. Чтобы указать, куда с выводимой строке должно вставляться значение, используйте поля в фигурных скобках {  }. Поле с переменной {average} преобразует значение переменной average в строковое представление, а затем меняет {average} на заменяющий текст. В форматной строке за переменной (выражением) может следовать двоеточие (:) и форматный спецификатор, который описывает, как должен форматироваться заменяющий текст. Форматный спецификатор .2f форматирует average  при выводе как число с плавающей точкой (f) с двумя цифрами в дробной части (.2). Выражения в фигурных скобках (в поле) могут содержать значения, переменные или другие выражения (например, вычисления или вызовы функций).

В приведенном примере спецификатор ‘.2f’ определял тип представления переменной. Существуют и другие типы представлений (b, o, x и X), форматирующие целые числа для представления в двоичной, восьмеричной и шестнадцатеричной системах счисления. 

Чтобы узнать, какие методы Python предоставляет для работы с тем или иным типом данных, используйте команду dir. Например, перечень методов для работы со строками можно получить, напечатав:

s=’abc’
dir(s)

Чтобы получить описание того или иного метода используйте help, например: 

In [25]:
help(s.find)

Help on built-in function find:

find(...) method of builtins.str instance
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.



#### Контейнеры

Python включает несколько встроенных типов контейнеров: списки, словари, множества и кортежи.

##### Списки

В списках (класс list) хранится последовательность изменяемых элементов. Он может изменять размер и может содержать элементы разных типов. Обращение к элементам списков выполняется с помощью индексов в квадратных скобках, например fruits[0] – первый элемент списка. 

In [26]:
fruits = ['apple', 'orange', 'pear', 'banana']  # создание списка
fruits[0]                                       # обращение по индексу 


'apple'

Python также допускает использование отрицательных индексов для обращения к элементам с конца списка. Например,  обращение к последнему и предпоследнему элементам списка: 

In [27]:
print(fruits[-1])  #1-ый с конца
print(fruits[-2])  #2-ой с конца

banana
pear


Можно индексировать несколько смежных элементов списка одновременно с помощью операторов среза (сегментирования). Например, fruits[1:3] возвращает список, содержащий элементы в позициях 1 и 2. В общем, fruits[start: stop] вернет элементы в позициях start, start + 1, ..., stop-1. Обращение fruits[start:] вернет все элементы списка, начиная с индекса start. Также fruits[:end] вернет все элементы c начала списка и до элемента в позиции end. Примеры:

In [28]:
fruits=['apple', 'orange', 'pear', ' banana']
print(fruits[0:2])  #['apple', 'orange']
print(fruits[:3])   #['apple', 'orange', 'pear']
print(fruits[2:])   #['pear', 'banana']
print(fruits[0:-1]) #['apple', 'orange', 'pear']
print(fruits[:])    #['apple', 'orange', 'pear', ' banana']
fruits[1:3]=['appricot', 'peach'] #замена нескольких значений в сегменте
print(fruits)
len(fruits)  #4

['apple', 'orange']
['apple', 'orange', 'pear']
['pear', ' banana']
['apple', 'orange', 'pear']
['apple', 'orange', 'pear', ' banana']
['apple', 'appricot', 'peach', ' banana']


4

Можно создать список из целых чисел с помощью функций range() и list(). При этом вызов функции range(5) создает итерируемый объект, который формирует последовательность целых чисел от 0 и до значения аргумента 5, не включая последний, в данном случае 0, 1, 2, 3, 4. Функция list создает из этой последовательности чисел список:

In [29]:
nums=list(range(5)) #range формирует последовательность от 0 до 4
print(nums)

[0, 1, 2, 3, 4]


Для работы со списками в Python имеется большой набор встроенных методов. Например:

In [30]:
print(fruits)
print(fruits.pop())				        #удаляет последний эл-т и возвращает его
print(fruits)					        #состояние списка после pop
fruits.append('grapefruit')		        # добавляет в конец спиcка
print(fruits)    	                    #состояние списка после добавления
fruits[-1] = 'pineapple'			    #заменить последний эл-т
print(fruits)                       	#состояние после замены
fruits. insert(0, 'grapefruit')	        #вставка эл-та в заданную позицию
print(fruits)
fruits.sort()                           #сортировка по возрастанию
print(fruits)
fruits.sort(reverse=True)               #сортировка по убыванию
print(fruits)

['apple', 'appricot', 'peach', ' banana']
 banana
['apple', 'appricot', 'peach']
['apple', 'appricot', 'peach', 'grapefruit']
['apple', 'appricot', 'peach', 'pineapple']
['grapefruit', 'apple', 'appricot', 'peach', 'pineapple']
['apple', 'appricot', 'grapefruit', 'peach', 'pineapple']
['pineapple', 'peach', 'grapefruit', 'appricot', 'apple']


Часто бывает нужно определить, содержит ли список (последовательность) значение, соответствующее заданному ключу поиска. У списков имеется метод index, которому передается ключ поиска в качестве аргумента. Метод начинает поиск с индекса 0 и возвращает индекс первого элемента, который равен ключу поиска. Если искомое значение отсутствует в списке, то происходит ошибка ValueError. 

In [31]:
numbers = [3, 7, 1, 4, 2, 8, 5, 6]
numbers.index(5)			           # 5 – ключ поиска

6

Оператор in проверяет, содержит ли итерируемый объект, каковым является список, заданное значение:

In [32]:
print(1000 in numbers)
5 in numbers

False


True

Элементы, хранящиеся в списках, могут быть любого типа. Так, например, элементами списка могут быть списки:

In [33]:
lstOfLsts = [['a', 'b', 'c'], [1, 2, 3], ['one', 'two', 'three']]
print(lstOfLsts[1][2])      # выведет 3
print(lstOfLsts[0].pop())   # выведет 'с'
lstOfLsts

3
c


[['a', 'b'], [1, 2, 3], ['one', 'two', 'three']]

Как обычно, вы можете получить детальные сведения о методах обработки списков с использованием команд dir и help.

##### Циклы

Вы можете перебирать элементы списка, используя цикл. Например:

In [34]:
animals = ['cat', 'dog', 'monkey','horse']
for animal in animals:
    print(animal)

cat
dog
monkey
horse


Если вы хотите получить доступ к индексу каждого элемента в теле цикла, используйте встроенную функцию `enumerate`:

In [35]:
#animals = ['cat', 'dog', 'monkey']
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))

#1: cat
#2: dog
#3: monkey
#4: horse


##### Списковое включение

При программировании часто необходимо выполнять преобразование (**отображение**) одиного списка в другой. В качестве простого примера рассмотрим следующий код, который на основе списка чисел формирует список квадратов этих чисел:

In [36]:
nums = [0, 1, 2, 3, 4, 5]
squares = []
for x in nums:
    squares.append(x ** 2)
print(squares)

[0, 1, 4, 9, 16, 25]


Для отображения одного списка в другой в Python используют более эффективноную конструкцию **спискового включения** (list comprehensions), которая обеспечивает компактную замену конструкции с for:

In [37]:
nums = [0, 1, 2, 3, 4, 7]
squares = [x ** 2 for x in nums]  # списковое включение
print(squares)

[0, 1, 4, 9, 16, 49]


Другая распространенная операция со списками — это **фильтрация** элементов списка и отбор только тех элементов, которые удовле-творяют заданному условию. Как правило, при этом строится список с меньшим количеством элементов, чем в исходном списке. Чтобы выполнить подобную операцию с использованием спискового включения, используйте секцию if. Следующий фрагмент кода демонстрирует простое отображение и фильтрацию с помощью спискового включения:

In [38]:
nums = [0, 1, 2, 3, 4, 7, 8]
even_squares = [x ** 2 for x in nums if x % 2 == 0] # создание списка квадратов четных элементов
print(even_squares)

[0, 4, 16, 64]


##### Словари

Словарь (класс dict) хранит пары *ключ:значение*, заключаемые в фигурные скобки. Ключ должен быть неизменяемым типом (строка, число или кортеж). Значение может быть любым типом данных Python. Примеры основных операций со словарями:

In [39]:
d = {'cat': 'cute', 'dog': 'furry'}  # Создание словаря
print(d['cat'])       # Поиск значения по ключу 'cat' в словаре d и печать найденного значения 'cute'
print('cat' in d)     # Проверка вхождения заданного ключа в словарь и печать True

cute
True


In [40]:
d['fish'] = 'wet'    # Добавление пары 'fish':'wet' в словарь d
print(d['fish'])    # Поиск значения ключа fish и печать результата 'wet'

wet


In [41]:
print(d['monkey'])  # Ошибка KeyError, если ключ отсутствует в словаре

KeyError: 'monkey'

In [42]:
print(d.get('monkey', 'N/A'))  # Извлечение значения по ключу, если ключ отсутвует то печать 'N/A'
print(d.get('fish', 'N/A'))    

N/A
wet


In [43]:
del d['fish']        # Удаление элемента (ключ:значение) из словаря
print(d.get('fish', 'N/A')) # "fish" больше не является ключом; печать "N/A"

N/A


Пример поиска значений в словаре с перебором ключей в цикле:

In [44]:
d = {'человек': 2, 'кошка': 4, 'паук': 8}
for animal in d:
    legs = d[animal]
    print('%s имеет %d ног(и)' % (animal, legs))

человек имеет 2 ног(и)
кошка имеет 4 ног(и)
паук имеет 8 ног(и)


Если вы хотите получить одновременный доступ к ключам и соответствующим значениям, используйте метод items. Обратите внимание, что метод items возвращает пары ключ:значение – в форме списка кортежей:

In [45]:
d = {'человек': 2, 'кошка': 4, 'паук': 8}
print(d.items())
for animal, legs in d.items():
    print('%s имеет %d ног(и)' % (animal, legs))

dict_items([('человек', 2), ('кошка', 4), ('паук', 8)])
человек имеет 2 ног(и)
кошка имеет 4 ног(и)
паук имеет 8 ног(и)


При работе со словарями можно использовать **словарные включения**, которые похожи на списковые включения. Например:

In [46]:
nums = [0, 1, 2, 3, 4, 5]
even_num_to_square = {x: x ** 2 for x in nums if x % 2 == 0}
print(even_num_to_square)

{0: 0, 2: 4, 4: 16}


##### Множества

Множество в Python (класс set) – это неупорядоченная последовательность неповторяющихся элементов, разделяемых запятыми и заключаемыми в фигурные скобки:

In [47]:
animals = {'cat', 'dog'}  # Создание множества
print(animals) 
type(animals)

{'cat', 'dog'}


set

Множество можно также создать из списка с помощью функции set:

In [48]:
shapes = ['circle', 'square', 'triangle', 'circle']  # список элементов
setOfShapes = set(shapes)                            # создание множества из списка                     
print(setOfShapes)

{'square', 'circle', 'triangle'}


Ниже представлены примеры, как добавлять/удалять элементы  множества, проверять, входит ли элемент во множество, и выполнять операции над множествами (разность, пересечение, объединение):

In [49]:
setOfShapes.add('polygon')				                        # добавление элемента
print('Рез-т добавления мн-во 1:', setOfShapes)
print('Круг входит:','circle' in setOfShapes)					# проверка принадлежности
print('Ромб входит:','rhombus' in setOfShapes)
favoriteShapes = ['circle', 'triangle', 'hexagon']               
setOfFavoriteShapes = set(favoriteShapes)                       # создание мно-ва 2
print('Мно-во 2:', setOfFavoriteShapes)
print('Разность:', setOfShapes - setOfFavoriteShapes)			# разность множеств
print('Пересечение:', setOfShapes & setOfFavoriteShapes)		# пересечение множеств
print('Объединение:',setOfShapes | setOfFavoriteShapes)			# объединение множеств
print('Удаление из мно-ва 1 элемента "polygon":')
setOfShapes.remove('polygon')                                   # удаление элемента
print(setOfShapes)

Рез-т добавления мн-во 1: {'polygon', 'square', 'circle', 'triangle'}
Круг входит: True
Ромб входит: False
Мно-во 2: {'hexagon', 'circle', 'triangle'}
Разность: {'square', 'polygon'}
Пересечение: {'circle', 'triangle'}
Объединение: {'polygon', 'square', 'triangle', 'hexagon', 'circle'}
Удаление из мно-ва 1 элемента "polygon":
{'square', 'circle', 'triangle'}


*Циклы*: Итерация по множеству имеет тот же синтаксис, что и итерация по списку; однако, поскольку множества неупорядочены, вы не можете знать о порядке, в котором вы выбираете элементы множества:

In [50]:
animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))       # Печатает "#1: fish", "#2: dog", "#3: cat"

#1: fish
#2: cat
#3: dog


**Включения множества**. Подобно спискам и словарям, мы можем легко создавать множества с использованием влючения множества:

In [51]:
from math import sqrt
print({int(sqrt(x)) for x in range(37)})   # множество целочисленных корней чисел из диапазона 1..37

{0, 1, 2, 3, 4, 5, 6}


##### Кортежи

Кортеж (класс tuple) – упорядоченный список значений, отличающийся от списка тем, что может быть использован в качестве ключа в словаре и в качестве элемента множества. Чтобы создать пустой кортеж, используйте пустые круглые скобки. Для упаковки элементов в кортеж можно просто перечислить их, разделяя запятыми. При создании элементы кортежа также можно заключать в круглые скобки (хотя это и не обязательно). Когда Python выводит кортеж, он всегда отображает его содержимое в круглых скобках. Примеры:

In [52]:
student_tuple = ()                       # пустой кортеж
len(student_tuple)

student_tuple = 'John', 'Green', 3.3	# создание кортежа
print(student_tuple)
print(student_tuple[0])				    # обращение по индексу к элементу кортежа

pair = (3, 5)  		                    # упаковка значений в кортеж
x, y = pair 		                    # распаковка (извлечение) кортежа
print(x, y)



('John', 'Green', 3.3)
John
3 5


In [53]:
d = {(x, x + 1): x for x in range(10)}  # Создание словаря с ключами в виде кортежей
t = (5, 6)                              # Прямое создание кортежа
print(type(t))
print(d[t])                             # Поиск в словаре по ключу (5,6)     
print(d[(1, 2)])                        # Поиск в словаре по ключу (1,2)

<class 'tuple'>
5
1


Кортеж похож на список, за исключением того, что это неизменяемая структура. Попытка изменить неизменяемую структуру вызывает исключение:

In [54]:
student_tuple[0]='Nick'

TypeError: 'tuple' object does not support item assignment

Тем не менее, можно добавлять элементы в кортеж, кортежи могут содержать изменяемые объекты: 

In [55]:
tuple1 = (10, 20, 30)
print('Кортеж 1:',tuple1)
tuple2 = tuple1		                   # tuple 2 и tulple 1 ссылаются на один и тот же кортеж
print('Кортеж 2:',tuple2)
# добавление элементов в кортеж
tuple1 += (40, 50)	                   # справа от += должен быть кортеж
print('Кортеж 1:',tuple1)
print('Кортеж 2:',tuple2)
# изменение списка в составе кортежа
student_tuple = ('Amanda', 'Blue', [98, 75, 87])
student_tuple[2][1] = 85               # элемент-список может изменяться
student_tuple

Кортеж 1: (10, 20, 30)
Кортеж 2: (10, 20, 30)
Кортеж 1: (10, 20, 30, 40, 50)
Кортеж 2: (10, 20, 30)


('Amanda', 'Blue', [98, 85, 87])

#### Функции

Функции Python определяются с помощью ключевого слова `def`. Например:

In [56]:
# определение функции
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))             # вызов функции

negative
zero
positive


Часто определяют функции с необязательными аргументами, например:

In [57]:
def hello(name, loud=False):                # loud - необязательный аргумент, по умолчанию loud=False
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob')
hello('Fred', loud=True)

Hello, Bob
HELLO, FRED!


#### Классы


Класс инкапсулирует данные и функции для взаимодействия с этими данными. Пример определения класса:

In [58]:
class Greeter:

    # Конструктор
    def __init__(self, name):
        self.name = name  # Атрибут класса

    # Метод класса
    # печатает приветствие строчными или заглавными буквами
    def greet(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = Greeter('Fred')  # Создание объекта (экземпляра класса) путем вызова конструктура класса Greeter
g.greet()            # Вызов метода объекта, печать "Hello, Fred"
g.greet(loud=True)   # Вызов метода объекта, печать "HELLO, FRED!"

Hello, Fred
HELLO, FRED!


Возможна работа  с иерархией классов. В этом случае метод-конструктор __init__ каждого подкласса должен явно вызвать метод __init__ своего базового класса, чтобы инициализировать атрибуты данных, унаследованные от базового класса. Этот вызов должен быть первой командой в методе __init__ определяемого подкласса. Для такого вызова используется обязательная запись super().__init__ , которая применяет встроенную функцию super для поиска и вызова метода __init__ базового класса. Пример определения заголовка класса наследника Greeter:

In [59]:
"""
class СolorGreeter(Greeter):        # Базовым классом является Greeter
    # Конструктор
    def __init__(self,name, color):
        super().__init__(name)      # вызов конструктора базового класса
"""

'\nclass СolorGreeter(Greeter):        # Базовым классом является Greeter\n    # Конструктор\n    def __init__(self,name, color):\n        super().__init__(name)      # вызов конструктора базового класса\n'

##### <font color='red'>Задание</font>

Создать класс, реализующий функционал учета рейтинга студентов **StudentsRating**. Класс должен иметь конструктор, который будет принимать список студентов с результатами сданных экзаменов, реализованый в виде словаря с ключем "ФИО студента" и оценками по экзаменам по 4 предметам (Программирование, Дискретная математика, Иностранный язык, Философия), представленными в виде кортежа. Например:

`{"Иванов Петр Николаевич":(3,3,5,4), "Петров Иван Константинович":(5,4,5,4)}`

Релизовать методы: 
- добавления студента с экзаменационными оценками;
- удаления студента из рейтинга; 
- получениe списка студентов с рейтингом выше порогового;
- демонстрации работы методов класса с выводом результатов на печать в виде текстовой таблицы.

Примечание:
Рейтинг - сумма баллов по всем предметам.

In [60]:
class StudentsRating():
    
    # Конструктор класс
    def __init__(self, students):
        self.students = students

    # Добавление студента
    def add_student(self, name, scores):
        self.students[name] = scores

    # Удаление студента
    def remove_student(self, name):
        del self.students[name]

    # Получение списка студентов с рейтингом выше порогового
    def get_higher_scores(self, threshold):
        return [name for name, scores in self.students.items() if sum(scores) > threshold]

    # Печать таблицы с рейтингом студентов
    def print_rating_table(self):
        print("Рейтинг студентов:")
        
        print("{:<30} {:<12} {:<12} {:<10} {:<10} {:<10}".format(
            "Имя", "Програм-ние", "Дискр. мат.", "Ин. язык", "Философия", "Всего")
        )

        for name, scores in self.students.items():
            total_score = sum(scores)
            print("{:<30} {:<12} {:<12} {:<10} {:<10} {:<10}".format(
                name, scores[0], scores[1], scores[2], scores[3], total_score)
            )  

In [61]:
d = {"Иванов Петр Николаевич": (3, 3, 5, 4), "Петров Иван Константинович": (5, 4, 5, 4)}
rating = StudentsRating(d)

rating.add_student("Васин Илья Никитич", (5, 5, 5, 5))
rating.add_student("Брахназаров Святан Кузнеевич", (2, 2, 3, 5))
rating.remove_student("Петров Иван Константинович")

print(*rating.get_higher_scores(12), sep='\n', end='\n\n')
rating.print_rating_table()

Иванов Петр Николаевич
Васин Илья Никитич

Рейтинг студентов:
Имя                            Програм-ние  Дискр. мат.  Ин. язык   Философия  Всего     
Иванов Петр Николаевич         3            3            5          4          15        
Васин Илья Никитич             5            5            5          5          20        
Брахназаров Святан Кузнеевич   2            2            3          5          12        


### Библиотека NumPy

NumPy - это основная библиотека для научных вычислений на Python. Она предоставляет высокопроизводительный объект многомерных массивов и инструменты для работы с этими массивами. 

Чтобы использовать Numpy, сначала нужно импортировать пакет `numpy`:

In [2]:
import numpy as np

#### Массивы

Массив NumPy представляет собой сетку элементов одного типа. Эта структура данных является ключевым компонентом библиотеки NumPy. Элементы массива NumPy индексируются кортежем целых неотрицательных чисел. Массивы NumPy похожи на списки Python, за исключением того, что они требуют меньше памяти и обычно быстрее, поскольку используют оптимизированный,прекомпилированный код на языке C

Число измерений - это ранг массива; форма массива представляет собой набор целых чисел, дающий размер массива вдоль каждого измерения.

Мы можем инициализировать массивы numpy, используя списки Python, и обращаться к элементам массивов с использованием индексов в квадратных скобках, индексация начинается с нуля:

In [63]:
a = np.array([1, 2, 3])                     # создание массива ранга 1 (вектора)
print(type(a), a.shape, a[0], a[1], a[2])   # вывод типа данных, формы массива, значений отдельных элементов массива
a[0] = 5                                    # Изменение значения элемента массива по индексу
print(a)                  

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [64]:
b = np.array([[1, 2, 3], [4, 5, 6]])             # Создание массива ранга 2 (матрицы)
print(b)

[[1 2 3]
 [4 5 6]]


In [65]:
print(b.shape)                     # вывод формы массива --> кортеж (2, 3)               
print(b[0, 0], b[0, 1], b[1, 0])   # вывод элементов матрицы: первая цифра - номер строки, вторая - номер столбца

(2, 3)
1 2 4


Numpy также предоставляет множество функций для создания массивов:


In [66]:
a = np.zeros((2, 2))  # Создание массива со всеми нулями
print(a)

[[0. 0.]
 [0. 0.]]


In [67]:
b = np.ones((1, 2))   # Создание массива со всеми единицами
print(b)

[[1. 1.]]


In [68]:
c = np.full((2, 2), 7) # Создание массива с заполнением заданными константами
print(c)

[[7 7]
 [7 7]]


In [69]:
d = np.eye(2)        # Создание единичной матрицы, размером 2x2 
print(d)

[[1. 0.]
 [0. 1.]]


In [3]:
e = np.random.random((2, 2)) # Создание массива из вещественных случайных чисел в диапазоне [0,1) с равномерным распределением
print(e)

[[0.4214139  0.51422886]
 [0.34047453 0.24837819]]


#### Типы данных

Каждый массив numpy представляет собой набор элементов одного типа. Numpy предоставляет большой набор числовых типов данных, которые можно использовать для построения массивов. Numpy пытается угадать тип данных при создании массива, но функции, которые строят массивы, обычно также включают необязательный аргумент, чтобы явно указать тип данных. Например:

In [71]:
x = np.array([1, 2])      # numpy определяет тип элемента по форме его записи (int32 - целый тип 32 бита)
y = np.array([1.0, 2.0])  # numpy определяет тип элемента по форме его записи (float64 - вещественный тип 64 бита)
z = np.array([1, 2], dtype=np.int64)  # Тип данных указан явно (int64 - целый тип 64 бита)

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


Вы можете прочитать все о типах данных numpy в [документации](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

#### Атрибуты массивов

При работе с массивами библиотеки NumPy можно получить полезную информацию о форме, размерностях массива, о типах данных элементов и занимаемом объеме данных. Примеры:

In [72]:
# создание массивов
np.random.seed(0)  # начальное значение генератора случайных чисел для целей воспроизводимости
x1 = np.random.randint(10, size=6)          # одномерный случайный целочисленный массив с равномерным распределением [0,10)
print('x1=', x1)
x2 = np.random.randint(10, size=(3, 4))     # аналогичный двумерный массив
print('x2=',x2)
x3 = np.random.randint(10, size=(3, 4, 5))  # аналогичный трехмерный массив

x1= [5 0 3 3 7 9]
x2= [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [73]:
# вывод атрибутов массива x3
print("x3 ndim: ", x3.ndim)  # число измерений - ранг 3
print("x3 shape:", x3.shape) # форма массива    - (3,4,5)
print("x3 size: ", x3.size)  # число элементов - 3х4х5=60

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [74]:
print("dtype:", x3.dtype) # тип элемента массива

dtype: int32


In [75]:
print("itemsize:", x3.itemsize, "bytes") # размер элемента массива в байтах 

itemsize: 4 bytes


In [76]:
print("nbytes:", x3.nbytes, "bytes") # кол-во байтов, занимаемых массивом

nbytes: 240 bytes


##### <font color=red>Задание</font>
Создать массив значений типа int32 размером 10х10, состоящий из равномерно распределенных случайных чисел от 0 до 100. Получить 4 копии этого массива со значениями типов: uint32,int64,uint64,float64. Преобразования типов выполняйте с помощью вызовов соответсвующих функций библиотеки NumPY, например: np.float64. Для каждого из массивов вывести сведения: число размерностей, форма, число элементов, тип данных, размер каждого элемента в байтах и размер всего массива в байтах.

In [77]:
import numpy as np

# Основной массив
int32_array = np.random.randint(0, 101, size=(10, 10), dtype=np.int32)

# Создание копий массива с другими типами данных
uint32_array = int32_array.astype(np.uint32)
int64_array = int32_array.astype(np.int64)
uint64_array = int32_array.astype(np.uint64)
float64_array = int32_array.astype(np.float64)

# Список созданных массивов
arrays = [int32_array, uint32_array, int64_array, uint64_array, float64_array]

# Перебор списка массивов и вывод сообщений
for array in arrays:
    print("Тип данных:", array.dtype)
    print("Число размерностей:", array.ndim)
    print("Форма:", array.shape)
    print("Число элементов:", array.size)
    print("Размер элемента (в байтах):", array.itemsize)
    print("Размер массива (в байтах):", array.nbytes)
    print()

Тип данных: int32
Число размерностей: 2
Форма: (10, 10)
Число элементов: 100
Размер элемента (в байтах): 4
Размер массива (в байтах): 400

Тип данных: uint32
Число размерностей: 2
Форма: (10, 10)
Число элементов: 100
Размер элемента (в байтах): 4
Размер массива (в байтах): 400

Тип данных: int64
Число размерностей: 2
Форма: (10, 10)
Число элементов: 100
Размер элемента (в байтах): 8
Размер массива (в байтах): 800

Тип данных: uint64
Число размерностей: 2
Форма: (10, 10)
Число элементов: 100
Размер элемента (в байтах): 8
Размер массива (в байтах): 800

Тип данных: float64
Число размерностей: 2
Форма: (10, 10)
Число элементов: 100
Размер элемента (в байтах): 8
Размер массива (в байтах): 800



#### Индексация массивов

Numpy предоставляет несколько способов индексации  массивов

**Индексация срезами** (сегментированием). Иногда для обозначения этого способа индексации массивов используют англоязычное слово  слайсинг(slising). Подобно спискам Python, при обращении к массивам numpy можно использовать срезы. Поскольку массивы могут быть многомерными, вы должны указать срез (сегмент) для каждого измерения массива:

In [2]:
import numpy as np

# Создание 2D массива с формой (3, 4)
# [[1  2  3  4]
#  [5  6  7  8]
#  [9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Использование сегментирования для обращения к подмассиву, содержащему выборку элементов 
# из первых 2-х строк и столбцов 1 и 2; подмассив b будет иметь форму (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

[[2 3]
 [6 7]]


Срез является некоторым **представлением** (видом) исходного массива, поэтому его изменение изменит исходный массив.

In [3]:
print(a[0, 1])  # печатает 2
b[0, 0] = 77    # b[0, 0] это на самом деле элемент a[0, 1] исходного массива 
print(a[0, 1])  # изменение b[0, 0] приводит к изменению a[0, 1], поэтому печатает 77

2
77



Вы также можете комбинировать индексирование целыми числами и индексацию срезами. Однако при этом будет получен массив меньшего ранга, чем исходный массив:

In [4]:
# Создание 2D массива с формой (3, 4)
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Два способа доступа к данным в средней строке массива.
Комбинирование целых индексов с индексацией срезами дает массив более низкого ранга,
в то время как использование только срезов дает массив того же ранга, что и
исходный массив:

In [5]:
row_r1 = a[1, :]    # Представление ранга 1 для второй строки матрицы a  
row_r2 = a[1:2, :]  # Представление ранга 2 для второй строки матрицы a 
row_r3 = a[[1], :]  # Представление ранга 2 для второй строки матрицы a 
print(row_r1, row_r1.shape) 
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


##### <font color=red>Задание</font>
Выполнить следующий код и объяснить результаты.

In [82]:
col_r1 = a[:, 1]            # комбинирование видов индексации
col_r2 = a[:, 1:2]          # индексация срезами
print(col_r1, col_r1.shape) 
print()                     
print(col_r2, col_r2.shape) 

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


*Написать обьяснение:*

В переменной col_r1 расположен массив, полученный из исходного комбинированием индексации целым числом и индексации срезами, поэтому его ранг ниже, чем у исходного.

Массив в переменной col_r2 был получен исключительно индексацией срезами, поэтому, несмотря на то, что он содержит те же элементы исходного массива, его ранг остался неизменен.

**Индексирование целочисленным массивом**: при индексировании массивов numpy с использованием срезов (сегментирования) результирующее представление массива всегда будет подмассивом исходного массива. 
Напротив, индексирование с помощью целочисленного массива позволяет создавать произвольные массивы с использованием данных из другого массива. Например:

In [11]:
a = np.array([[1, 2], [3, 4], [5, 6]])

# Пример индексации с помощью массива из целых чисел.
# Форма возвращаемого массива будет равна (3,)  
print(a[[0, 1, 2], [0, 1, 0]])

# Вышеприведенный пример индексации целочисленным массивом эквивалентен следующему:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [84]:
# Если используется индексация целочисленным массовом, то 
# можно повторно использовать элементы исходного массива:
print(a[[0, 0], [1, 1]])

# Это эквивалентно повторному обращению элементу:
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


Один полезный трюк с использованием индексированиия в виде целочисленного массива - это выбор или изменение элемента массива в каждой его строке:

In [12]:
# Создание нового массива, из которого будем выбирать элементы
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
# Создание массива индексов
b = np.array([0, 2, 0, 1])

# Выбор одного элемента из каждой строки массива "a" с помощью индексов из массива "b"
print(a[np.arange(4), b])  # Печатает "[ 1  6  7 11]"

[ 1  6  7 11]


In [87]:
# Изменение элемента в каждой строке массива "a" в позициях с индексами из массива "b"
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


Иногда при индексации при помощи срезов бывает полезно работать не с представлением исходного массива, а иметь новый независимый подмассив из данных исходного массива. Тогда нужно скопировать представление массива при помощи метода `copy`.

In [88]:
x = np.random.randint(10, size=(3, 4))
x_sub_copy = x[:2, :2].copy()
print(x_sub_copy)

[[9 8]
 [5 9]]


**Индексирование при помощи булевых массивов**: индексирование при помощи булевых массивов позволяет выбирать произвольные элементы массива. Часто этот тип индексации используют для выбора элементов массива, которые удовлетворяют некоторому условию. Вот пример:

In [89]:
import numpy as np

a = np.array([[1, 2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Находит элементы больше, чем 2
                    # и возвращает numpy массив логических значений 
                    # той же формы, что и массив "a", при этом каждая позиция bool_idx сообщает
                    # действительно ли тот или иной элемент массива "а"  >  2.

print(bool_idx)     # печать массива логических значений

[[False False]
 [ True  True]
 [ True  True]]


In [90]:
# Выполним индексацию с помощью логического массива и созданим массив ранга 1, 
# который будет состоять из элементов исходного массива, в позициях которых
# логический  массив bool_idx содержит значения True
print(a[bool_idx])

# Можно также все это выполнить весьма лаконично в одном выражении:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


##### <font color=red>Задание</font>
Создать массив случайных целочисленных значений (от -100 до 100) размером 8x8. Используя индексацию булевыми (логическими) массивами получить:
1. Все элементы, значения которых являются четными числами. Вывести их маску в виде логического массива.
2. Все элементы, значения которых попадают в диапазон от 10 до 50. Вывести их маску в виде логического массива.
3. Все элементы, значения которых являются четными числами и попадают в диапазон от 10 до 50. Вывести их маску в виде логического массива.
4. Все элементы, значения которых являются нечетными числами и модуль значения которых из диапазона от 10 до 50. Вывести их маску в виде логического массива.
5. Все элементы, значения которых являются нечетными числами или отрицательными.

При необходимости выполнения логических операций над булевыми массивами NumPy используйте соответсвующие логические функции этой библиотеки: np.logical_not, np.logical_and, np.logical_or, np.logical_xor.

In [91]:
# Выполнение задания
import numpy as np

# Создание массива
arr = np.random.randint(-100, 101, size=(8, 8))
print("Массив:")
print(arr, end='\n\n')

# Маска чётных чисел
mask1 = np.mod(arr, 2) == 0
print("Маска чётных чисел:")
print(mask1, end='\n\n')

# Маска диапазона [10; 50]
mask2 = np.logical_and(arr >= 10, arr <= 50)
print("Маска чисел в диапазоне [10; 50]:")
print(mask2, end='\n\n')

# Маска чётных чисел, в диапазоне [10; 50]
mask3 = np.logical_and(mask1, mask2)
print("Маска чётных чисел в диапазоне [10; 50]:")
print(mask3, end='\n\n')

# Маска нечётных чисел, модуль в диапазоне [10; 50]
mask4 = np.logical_and(np.logical_not(mask1), np.logical_and(np.abs(arr) >= 10, np.abs(arr) <= 50))
print("Маска нечётных чисел с модулем в диапазоне [10; 50]:")
print(mask4, end='\n\n')

# Нечётные или отрицательные числа
mask5 = np.logical_or(np.logical_not(mask1), arr < 0)
print("Нечётные или отрицательные числа:")
print(arr[mask5])

Массив:
[[  4  60  21 -30 -69 -87 -29  84]
 [ 52 -21 -59 -82 -60  82 -89  66]
 [ 11  -7  29  18 -56  25 -76 -33]
 [-97 -65  89  97 -57 -68 -89   4]
 [ 38  82  65  25  56  11 -98 -73]
 [ 51 -47 -49  74  48  81 -71 -33]
 [-65 -61  37 -27 -59  51  31 -54]
 [ 78   8 -97 -69 -91  38 -73  73]]

Маска чётных чисел:
[[ True  True False  True False False False  True]
 [ True False False  True  True  True False  True]
 [False False False  True  True False  True False]
 [False False False False False  True False  True]
 [ True  True False False  True False  True False]
 [False False False  True  True False False False]
 [False False False False False False False  True]
 [ True  True False False False  True False False]]

Маска чисел в диапазоне [10; 50]:
[[False False  True False False False False False]
 [False False False False False False False False]
 [ True False  True  True False  True False False]
 [False False False False False False False False]
 [ True False False  True False  True Fals

Для краткости мы пропустили много деталей о индексации массива numpy; если вы хотите узнать больше, прочитайте документацию.

#### Изменение формы массивов

Часто требуется изменить форму массива (количество измерений и их значения), не изменяя самих элементов массива. Для этого используется специальный метод `reshape`.

In [92]:
grid = np.arange(1, 10)   # создание одномерного массива  [1 2 3 4 5 6 7 8 9]
print(grid)
grid = grid.reshape((3, 3)) # преобразование одномерного массива в двумерный с формой (3,3)
print(grid)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Часто требуется добавлять измерение в  массив. Например, когда необходимо привести одномерный массива к виду двумерной матрицы-строки или матрицы-столбца. Для этого можно применить метод reshape, но лучше воспользоваться специальным объектом np.newaxis, добавляющим новое измерение при выполнении операции среза. Примеры:

In [93]:
x = np.array([1, 2, 3]) 
print('Исходная форма x:', x.shape)
# Реформатирование в вектор-строку с помощью reshape
x.reshape((1, 3))   # форма (1, 3)

Исходная форма x: (3,)


array([[1, 2, 3]])

In [94]:
# Реформатирование в вектор-строку c помощью np.newaxis
x[np.newaxis, :]   # форма (1, 3)

array([[1, 2, 3]])

In [95]:
# Реформатирование в вектор-столбец с помощью reshape
x.reshape((3, 1))   # форма (3, 1)

array([[1],
       [2],
       [3]])

In [96]:
# Реформатирование в вектор-столбец с помощью np.newaxis
x[:, np.newaxis]   # форма (3, 1)

array([[1],
       [2],
       [3]])

#### Объединение массивов

Для объединения массивов можно использовать функции `np.vstack` (вертикальное объединение) и `np.hstack` (горизонтальное объединение):

In [97]:
x = np.array([1, 2, 3])                  # форма (3,)
grid = np.array([[9, 8, 7], [6, 5, 4]])  # форма (2,3)
# Создания стека массивов в вертикальном направлении
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [98]:
y = np.array([[99], [99]])              # форма (2,1)
# Создания стека массивов в горизотальном направлении
np.hstack([grid, y])


array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

Функция `np.dstack` аналогично объединяет массивы по третьей оси (глубине).

#### Разбиение массивов
Разбиение массивов, выполняется с помощью функций np.split, np.hsplit и np.vsplit. Каждой из них необходимо передавать список индексов, задающих точки разбиения:

In [99]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])  # 3 и 5 индексы элементов, относительно которых происходит разбиения
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Функции `np.hsplit` и `np.vsplit` выполняют аналогичную работу с учетом направления разбиения:

In [100]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
print('Исходная форма grid:', grid.shape)
upper, lower = np.vsplit(grid, [2]) # разбиение массива по вертикали относительно строки 2
print(upper)                        # верхняя часть массива - строки 0 и 1
print(lower)                        # нижняя часть массива  - строки 2 и 3

Исходная форма grid: (4, 4)
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [102]:
left, right = np.hsplit(grid, [2])  # разбиение массива по горизонтали относительно столбца 2
print(left)                         # левая часть массива - столбцы 0 и 1
print(right)                        # правая часть массива - столбцы 2 и 3

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##### <font color=red>Задание</font>
Написать функцию, которая из исходного массива размером 8х8 получает (при помощи операций разбиения и объединения) массив, в котором переставлены квадранты 1-й с 3-м, 2-й с 4-м по сравнению с исходным массивом. Продемонстрировать работу функции, все шаги алгоритма сопроводить подробными комментариями и отладочным выводом промежуточных результатов.

Т.е. например из массива

`[[49  5 49  1 28 27 31 35]
 [21 12 34  3 20  2 42 48]
 [21 22 39 23 28 31 47 34]
 [37  6 24 22 19 32 27 20]
 [12  0  1 40  2 30 42 47]
 [33 40 10  8 29 48 24  8]
 [14 49  8 46 23 18 10 49]
 [15 20 49 30  9 18 42  5]]`
 
должен получиться массив 

 `[[ 2 30 42 47 12  0  1 40]
 [29 48 24  8 33 40 10  8]
 [23 18 10 49 14 49  8 46]
 [ 9 18 42  5 15 20 49 30]
 [28 27 31 35 49  5 49  1]
 [20  2 42 48 21 12 34  3]
 [28 31 47 34 21 22 39 23]
 [19 32 27 20 37  6 24 22]]`

In [103]:
# Выполнение задания
import numpy as np

def swap_quadrants(arr):
    
    # Разделение массива на квадранты
    quadrants = np.split(arr, 2)
    quadrant1, quadrant2 = np.hsplit(quadrants[0], 2)
    quadrant4, quadrant3 = np.hsplit(quadrants[1], 2)

    # Вывод промежуточных результатов
    print("Квадрант 1:", quadrant1, sep='\n', end='\n\n')
    print("Квадрант 2:", quadrant2, sep='\n', end='\n\n')
    print("Квадрант 3:", quadrant3, sep='\n', end='\n\n')
    print("Квадрант 4:", quadrant4, sep='\n', end='\n\n')

    # Объединение квадрантов в новом порядке
    new_arr = np.vstack((np.hstack((quadrant3, quadrant4)),
                         np.hstack((quadrant2, quadrant1))))

    return new_arr

# Пример использования функции
arr = np.arange(1, 65).reshape(8, 8)

# Вывод исходного массива
print("Исходный массив:")
print(arr, end='\n\n')

# Вывод результирующего массива
result = swap_quadrants(arr)
print("Результирующий массив:")
print(result)

Исходный массив:
[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]

Квадрант 1:
[[ 1  2  3  4]
 [ 9 10 11 12]
 [17 18 19 20]
 [25 26 27 28]]

Квадрант 2:
[[ 5  6  7  8]
 [13 14 15 16]
 [21 22 23 24]
 [29 30 31 32]]

Квадрант 3:
[[37 38 39 40]
 [45 46 47 48]
 [53 54 55 56]
 [61 62 63 64]]

Квадрант 4:
[[33 34 35 36]
 [41 42 43 44]
 [49 50 51 52]
 [57 58 59 60]]

Результирующий массив:
[[37 38 39 40 33 34 35 36]
 [45 46 47 48 41 42 43 44]
 [53 54 55 56 49 50 51 52]
 [61 62 63 64 57 58 59 60]
 [ 5  6  7  8  1  2  3  4]
 [13 14 15 16  9 10 11 12]
 [21 22 23 24 17 18 19 20]
 [29 30 31 32 25 26 27 28]]


#### Вычисления с массивами

Основные математические функции выполняют поэлементную обработку массивов и доступны для вызовов как в форме перегруженных операторов, так и  в виде функций модуля numpy:

In [104]:
import numpy as np
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)

# Поэлементное сложение массивов одинаковой формы; оба вызова ниже возвращают массив 
print(x + y)         # вызов в форме пергруженного оператора суммирования 
print(np.add(x, y))  # вызов в  виде функции (метода) сложения

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [105]:
# Поэлементное вычитание массивов одинаковой формы; оба вызова ниже возвращают массив 
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [106]:
# Поэлементное произведение массивов одинаковой формы; оба вызова ниже возвращают массив 
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [107]:
# Поэлементное деление массивов одинаковой формы; оба вызова ниже возвращают массив 
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [108]:
# Поэлементное вычисление квадратного корня массива 
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


Обратите внимание, что в отличие от MATLAB, оператор произведения * выполняет поэлементное умножение, а не векторно-матричное умножение. Для вычисления скалярных произведений векторов, умножения матрицы на вектор и умножения матрицы на матрицу используют функцию (метод) dot. Вызов этой функции доступен в 2-х формах: 1) в виде вызова метода экземпляра класса массива; 2) в виде вызова функции модуля numpy:

In [109]:
# Создание массивов-матриц
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

# Создание массивов-векторов
v = np.array([9, 10])
w = np.array([11, 12])

print('Формы массивов:', 'x=', x.shape, 'y=', y.shape, 'v=', v.shape, 'w=', w.shape)

# Скалярное произведение векторов v*w равно сумме произведений их элементов: 9*11+10*12=219
print('Скалярное произведение векторов v*w:')
print(v.dot(w))      # 1) вызов метода dot объекта v (экземпляра класса массив)
print(np.dot(v, w))  # 2) вызов функции dot модуля numpy

Формы массивов: x= (2, 2) y= (2, 2) v= (2,) w= (2,)
Скалярное произведение векторов v*w:
219
219


In [110]:
# Произведение матрицы на вектор X*v, оба вызова ниже вернут вектор:  [1*9+2*10; 3*9+4*10]=[29 67]
print(x.dot(v))      # 1) вызов метода dot объекта x (экземпляра класса массив)
print(np.dot(x, v))  # 2) вызов функции dot модуля numpy

[29 67]
[29 67]


In [111]:
# Произведение матрицы X на матрицу Y, оба вызова ниже вернут матрицу ранга 2:
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy предоставляет множество полезных функций для выполнения вычислений с массивами; одна из часто используемых - это функция суммирования `sum`:

In [112]:
x = np.array([[1, 2], [3, 4]])

print(np.sum(x))          # вычисляет сумму всех элеентов x ; печатает "10"
print(np.sum(x, axis=0))  # вычисляет сумму элементов вдоль оси 0 (каждого столбца х); печатает "[4 6]"
print(np.sum(x, axis=1))  # вычисляет сумму элементов вдоль оси 1 (каждой строки х); печатает "[3 7]"

10
[4 6]
[3 7]


Полный список математических функций, предоставляемых numpy, содержится в [документации](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Помимо вычисления математических функций с использованием массивов, нам часто приходится изменять форму массива или иным образом манипулировать данными в массивах. Простейшим примером такой операции является транспонирование матрицы; для транспонирования матрицы просто используйте атрибут T объекта массива:

In [113]:
# Транспонирование матрицы
print(x)    # печать исходной матрицы
print(x.T)  # печать транспонированной матрицы

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [114]:
# Обратим внимание, что транспонирование массива ранга 1 ни к чему не приводит
v1 = np.array([1, 2, 3])
print(v1.shape, v1)    # печатает (3,) [1 2 3]
v2=v1.T.copy()         # транспонирование v1 и копирование в v2
print(v2.shape, v2)    # печатает (3,) [1 2 3]

(3,) [1 2 3]
(3,) [1 2 3]


#### Транслирование

**Транслирование** (broadcasting) - один из механизмов NumPy, предназначенный для векторизации операций, а следовательно устранения медленных стандартных циклов языка Python при работе с массивами. Транслирование представляет собой набор правил по применению бинарных универсальных функций (сложение, вычитание, умножение и т. д.) к массивам разных форм. 

Например, требуется выполнить сложение некоторого вектора с каждой строкой матрицы. Мы могли бы сделать это, используя явный цикл по строкам матрицы:

In [115]:
# Сложение вектора v с каждой строкой матрицы x,
# сохранение результата в матрице y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]) 
v = np.array([1, 0, 1])
y = np.empty_like(x)   # создание пустой матрицы у; той же формы, что и x

# Сложение вектора v с каждой строкой матрицы x с помощью явного цикла
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Это работает; однако, когда матрица x очень велика, вычисление явного цикла в Python может быть медленным. Заметим, что добавление вектора v в каждую строку матрицы x эквивалентно выполнению двух шагов: 1) формированию некоторой промежуточной матрицы vv путем складирования нескольких копий v одна поверх другой; 2) выполнение поэлементного сложения двух матриц x и vv. Мы могли бы реализовать этот подход следующим образом:

In [116]:
vv = np.tile(v, (4, 1))  # Складирование 4-х копий вектора v: одна поверх другой
print(vv)                # Печатает "[[1 0 1]
                         #           [1 0 1]
                         #           [1 0 1]
                         #           [1 0 1]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [117]:
y = x + vv  # Поэдементное сложение матриц одного размера x и vv 
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Транслирование позволяет нам выполнять эти вычисления без фактического создания нескольких копий v. Рассмотрим вариант решения задачи, использующий транслирование:

In [118]:
import numpy as np

# Использование механизма транслирования

# Сложение вектора v с каждой строкой матрицы x,
# сохранение результата в матрице y
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  #  Сложение вектора v с каждой строкой матрицы x путем транслирования
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


При транслировании строка кода `y = x + v` работает, даже если` x` имеет форму `(4, 3)` и `v` имеет форму` (3,)` ; эта строка кода работает так, как если бы переменная `v` фактически имела форму `(4, 3)`, где каждая строка была копией `v`, а сложение вычислялось поэлементно.

**Транслирование** двух массивов выполняется в соответствии с правилами:

1. Если массивы не одного ранга, то к форме массива меньшего ранга добавляется одно измерение слева до тех пор, пока формы массивов не будут иметь одинаковую длину.
2. Два массива, как говорят, совместимы в некотором измерении, если они имеют одинаковый размер в этом измерении, или если один из массивов имеет размер 1 в этом измерении.
3. Массивы могут транслироваться один в другой, если они совместимы во всех измерениях.
4. После трансляции каждый массив ведет себя так, как если бы он имел форму, равную поэлементному максимуму форм двух входных массивов.
5. В любом измерении, где один массив имел размер 1, а другой массив имел размер больше 1, первый массив ведет себя так, как если бы он был скопирован вдоль этого измерения.

В книге  `Плас Дж. Вандер Python для сложных задач: наука о данных и машинное обучение. — СПб.: Питер, 2018.-576c.`
транслирование массивов описывается тремя правилами:
1. Если размерность двух массивов отличается, форма массива с меньшей размерностью дополняется единицами с ведущей (левой) стороны.
2. Если форма двух массивов не совпадает в каком-то измерении, массив с формой, равной 1 в данном измерении, растягивается вплоть до соответствия форме другого массива.
3. Если в каком-либо измерении размеры массивов различаются и ни один не равен 1, генерируется ошибка.

Вот некоторые примеры использования трансляции:

In [119]:
# Вычисление внешнего произведения векторов v*w
v = np.array([1, 2, 3])  # форма v : (3,)
w = np.array([4, 5])     # форма w : (2,)

# Чтобы вычислить внешнее произведение. реформатируем сначала v в вектор-столбец с формой (3, 1);
# a затем выполняем транслирование с учетом формы w, чтобы получить массив формы (3, 2), 
# которую будет иметь внешнее произведение v и w:
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [120]:
# Сложение вектора с каждой строкой матрицы
x = np.array([[1, 2, 3], [4, 5, 6]])
# форма x: (2, 3) , форма v: (3,), следовательно они транслируются в форму (2, 3),
# формируя следующую матрицу-результат:
# [[2 4 6]
# [5 7 9]]

print(x + v)

[[2 4 6]
 [5 7 9]]


In [121]:
# Сложение вектора с каждым столбцом матрицы, где
# форма матрицы x: (2, 3) , форма вектора w: (2,).
# Если мы транспонируем x, то она будет иметь форму (3, 2) и будет возможно транслирование
# с учетом формы w, чтобы получить результат формы (3, 2); транспонирование этого результата
# дает окончательный результат формы (2, 3), который представляет собой матрицу x 
# в каждый столбец, которой добавлен вектор w:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)

[[ 5  6  7]
 [ 9 10 11]]


In [122]:
# Другое решение — реформатировать w в вектор-строку формы (2, 1);
# затем можно будет транслировать его непосредственно на x, чтобы получить тот же выход
print(x + np.reshape(w, (2, 1)))

[[ 5  6  7]
 [ 9 10 11]]


In [123]:
# Умножение матрицу на константу:
# форма x : (2, 3). Numpy рассматривает скалярные значения как массивы формы ();
# их можно транслировать в форму (2, 3), чтобы получить результирующий массив:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


Транслирование обычно делает ваш код более кратким и быстрым, поэтому вы должны стремиться использовать его там, где это возможно.

##### Трансляция. Пример 1.

Рассмотрим сложение двумерного массива с одномерным:
``` 
M = np.ones((2, 3))
a = np.arange(3)
```
Рассмотрим эту операцию подробнее. Формы массивов следующие:
```
M.shape = (2, 3)
a.shape = (3,)
```
По правилу 1, поскольку размерность массива `a` меньше, мы дополняем его измерением слева:
```
M.shape -> (2, 3)
a.shape -> (1, 3)
```
По правилу 2 мы видим, что первое измерение массивов различается, так что мы 
растягиваем размер `a` его вплоть до совпадения:
```
M.shape -> (2, 3)
a.shape -> (2, 3)
```
Формы совпадают, и мы видим, что итоговая форма будет (2, 3). Проверим:

In [124]:
M = np.ones((2, 3))
print('M=', M)
a = np.arange(3)
print('a=', a)
M+a

M= [[1. 1. 1.]
 [1. 1. 1.]]
a= [0 1 2]


array([[1., 2., 3.],
       [1., 2., 3.]])

##### Транслирование. Пример 2
Рассмотрим пример, в котором необходимо транслировать оба массива:
```
a = np.arange(3).reshape((3, 1))
a=[0
   1
   2]
b = np.arange(3)
b=[0 1 2]
```
Начнем с записи формы наших массивов:
```
a.shape = (3, 1)
b.shape = (3,)
```
Правило 1 гласит, что мы должны дополнить форму массива b измерением слева:
```
a.shape -> (3, 1)
b.shape -> (1, 3)
```
Правило 2 говорит, что нужно увеличивать размеры измерений вплоть до совпадения 
с размерами измерений другого массива:
```
a.shape -> (3, 3)
a=[0 0 0
   1 1 1
   2 2 2]

b.shape -> (3, 3)
b=[0 1 2
   0 1 2
   0 1 2]


```
Поскольку формы совпадают, массивы совместимы. Суммируя `a+b`, получаем:


In [125]:
a = np.arange(3).reshape((3, 1))
print('a=', a)
b = np.arange(3)
print('b=', b)
a+b

a= [[0]
 [1]
 [2]]
b= [0 1 2]


array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

##### Транслирование. Пример 3
Рассмотрим пример, в котором два массива несовместимы:
```
M = np.ones((3, 2))
a = np.arange(3)
```
Эта ситуация лишь немного отличается от примера 1: матрица M транспонирована. Какое же влияние это окажет на вычисления? Формы массивов следующие:
```
M.shape = (3, 2)
a.shape = (3,)
```
Правило 1 при транслировании дополняет форму массива `a` измерением слева:
```
M.shape -> (3, 2)
a.shape -> (1, 3)
```
Согласно правилу 2 первое измерение массива `a` растягивается, чтобы соответствовать таковому массива M:
```
M.shape -> (3, 2)
a.shape -> (3, 3)
```
Теперь вступает в действие правило 3 — итоговые формы не совпадают, так что массивы несовместимы, что мы и видим, попытавшись выполнить данную операцию:

In [126]:
M = np.ones((3, 2))
a = np.arange(3)
M+a

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

Обратите внимание на имеющийся потенциальный источник ошибки: можно было бы сделать массивы a и M совместимыми, скажем путем дополнения формы `a` единицами справа, а не слева. Но правила транслирования работают не так! 
Если вам необходимо применить правостороннее дополнение формы, можно сделать это явным образом, поменяв форму массива. Для этого воспользуемся специальным объектом `np.newaxis`:

In [127]:
a[:, np.newaxis].shape

(3, 1)

In [128]:
M + a[:, np.newaxis]

array([[1., 1.],
       [2., 2.],
       [3., 3.]])

Этот краткий обзор затронул многие важные вещи, которые вам нужно знать о NumPy, но далеко не всё. Чтобы узнать больше о NumPy смотрите [документацию по numpy](http://docs.scipy.org/doc/numpy/reference/).

##### <font color=red>Задание</font>
Возможна ли совместная трансляция массивов с формами:
1. (100,100,4) и (3) ?
2. (15,1,6,5) и (7,1,5) ?
3. (12,3,8) и (3,1) ?
4. (10,4,1,6) и (3,1,6) ?
5. (10,1) и (1,10,3) ?

Дать подробные ответы (аналогично примерам, приведенным выше) со ссылками на правила трансляции и сопроводить примерами с вычислениями и комментариями.

###### Задание 1
Формы массивов следующие:
```
a.shape = (100, 100, 4)
b.shape = (3)
```
Правило 1: при транслировании дополняем форму массива `b` измерениями слева:
```
a.shape -> (100, 100, 4)
b.shape -> (1, 1, 3)
```
Правило 2: первое и второе измерения массива `b` растягиваются, чтобы соответствовать таковому массива `a`:
```
a.shape -> (100, 100, 4)
b.shape -> (100, 100, 3)
```
Правило 3: формы не совпадают, трансляция невозможна.

In [129]:
a = np.ones((100, 100, 4))
b = np.ones(3)
print((a + b).shape)

ValueError: operands could not be broadcast together with shapes (100,100,4) (3,) 

###### Задание 2
Формы массивов следующие:
```
a.shape = (15, 1, 6, 5)
b.shape = (7, 1, 5)
```
Правило 1: при транслировании дополняем форму массива `b` измерением слева:
```
a.shape -> (15, 1, 6, 5)
b.shape -> (1, 7, 1, 5)
```
Правило 2: растягиваются второе измерение массива `a` и первое и третье измерение массива `b`:
```
a.shape -> (15, 7, 6, 5)
b.shape -> (15, 7, 6, 5)
```
Формы совпадают, трансляция возможна. Итоговая форма - (15, 7, 6, 5):

In [130]:
a = np.ones((15, 1, 6, 5))
b = np.ones((7, 1, 5))
print((a + b).shape)

(15, 7, 6, 5)


###### Задание 3
Формы массивов следующие:
```
a.shape = (12, 3, 8)
b.shape = (3, 1)
```
Правило 1: при транслировании дополняем форму массива `b` измерением слева:
```
a.shape -> (12, 3, 8)
b.shape -> (1, 3, 1)
```
Правило 2: растягиваются первое и третье измерения массива `b`:
```
a.shape -> (12, 3, 8)
b.shape -> (12, 3, 8)
```
Формы совпадают, трансляция возможна. Итоговая форма - (12, 3, 8):

In [131]:
a = np.ones((12, 3, 8))
b = np.ones((3, 1))
print((a + b).shape)

(12, 3, 8)


###### Задание 4
Формы массивов следующие:
```
a.shape = (10, 4, 1, 6)
b.shape = (3, 1, 6)
```
Правило 1: при транслировании дополняем форму массива `b` измерением слева:
```
a.shape = (10, 4, 1, 6)
b.shape = (1, 3, 1, 6)
```
Правило 2: растягивается первое измерение массива `b`:
```
a.shape = (10, 4, 1, 6)
b.shape = (10, 3, 1, 6)
```
Формы не совпадают, трансляция невозможна.

In [132]:
a = np.ones((10, 4, 1, 6))
b = np.ones((3, 1, 6))
print((a + b).shape)

ValueError: operands could not be broadcast together with shapes (10,4,1,6) (3,1,6) 

###### Задание 5
Формы массивов следующие:
```
a.shape = (10, 1)
b.shape = (1, 10, 3)
```
Правило 1: при транслировании дополняем форму массива `a` измерением слева:
```
a.shape -> (1, 10, 1)
b.shape -> (1, 10, 3)
```
Правило 2: третье измерение массива `a` растягивается, чтобы соответствовать таковому массива `b`:
```
a.shape -> (1, 10, 3)
b.shape -> (1, 10, 3)
```
Формы совпадают, трансляция возможна. Итоговая форма - (1, 10, 3).

In [133]:
a = np.ones((10, 1))
b = np.ones((1, 10, 3))
print((a + b).shape)

(1, 10, 3)


#### Универсальные функции

Функции, поддерживающие трансляцию, известны как **универсальные функции**. Вы можете найти список всех универсальных функций в [документации](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

**<font color=blue>Вычисления с применением векторизации посредством универсальных функций практически всегда более эффективны, чем их эквиваленты, реализованные с помощью циклов Python, особенно при больших размерах массивов.</font>**

* Арифметические функции над массивами

In [134]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # деление с округлением в меньшую сторону
print("-x     = ", -x)
print("x ** 2 = ", x ** 2) # возведение в степень
print("x % 2  = ", x % 2)  # остаток от деления

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


Дополнительно эти операции можно комбинировать любыми способами с соблюдением стандартного приоритета выполнения операций:


In [135]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

* Абсолютное значение.

Используется универсальная функция библиотеки NumPy — `np.absolute`, доступная также под псевдонимом `np.abs`:

In [136]:
x = np.array([0, -1, 2, -3])
np.absolute(x)

array([0, 1, 2, 3])

In [137]:
np.abs(x)

array([0, 1, 2, 3])

In [138]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j]) # массив комплексных чисел
np.abs(x)                                      # модуль комплексных чисел

array([5., 5., 2., 1.])

#### Указание массива для вывода результата
При  вычислениях c помощью универсальных функций удобно задать аргумент-массив, в котором будет сохранен результат вычислений, вместо того чтобы создавать временный массив в памяти в ходе вычислений. Сделать это для любой универсальной функции можно с помощью ключевого аргумента out:

In [139]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


Эту возможность можно использовать даже вместе с представлениями массивов. Например, можно записать результаты вычислений в каждый второй элемент выходного массива:

In [140]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


Если бы мы вместо этого написали `y[::2] = 2 ** x`, был бы создан временный массив для хранения результатов операции `2 ** x` с последующим копированием этих значений в массив y. Для столь незначительных объемов вычислений особой разницы нет, но для очень больших массивов экономия памяти за счет аккуратного использования аргумента out может оказаться значительной.

##### <font color=red>Задание</font>
Создать класс наследник от класса учета рейтинга студентов (**StudentsRaiting**) и расширить его методами рассчета статистики по предметам (средний балл, максимальный балл, минимальный балл). Для этого нужно преобразовать данные об оценках из словаря в массив и использовать функции библиотеки Numpy.

Примечание: Использовать универсальные функции для работы с массивами numpy.

In [141]:
# Выполнение задания
class StudentsRatingPro(StudentsRating):
    
    # Конструктор
    def __init__(self, students):
        super().__init__(students)
        self.scores = np.array(list(self.students.values()))

    # Расчет среднего балла по каждому предмету
    def get_averages(self): 
        return np.mean(self.scores, axis=0)
    
    # Расчет максимального балла по каждому предмету
    def get_maxes(self):
        return np.max(self.scores, axis=0)
        
    # Расчет минимального балла по каждому предмету
    def get_mins(self):
        return np.min(self.scores, axis=0)

In [144]:
d = {"Иванов Петр Николаевич": (3, 3, 5, 4), 
     "Петров Иван Константинович": (5, 4, 5, 4)}
rating = StudentsRatingPro(d)

averages = rating.get_averages()
maxes = rating.get_maxes()
mins = rating.get_mins()

print("\nСтатистика по предметам:")
print("Средние баллы:", *averages)
print("Максимальные баллы:", *maxes)
print("Минимальные баллы:", *mins)


Статистика по предметам:
Средние баллы: 4.0 3.5 5.0 4.0
Максимальные баллы: 5 4 5 4
Минимальные баллы: 3 3 5 4


##### <font color=red>Задание</font>
0. Создать функцию `Function1(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=1/(1+exp(-x)`. Создать функцию `Function2(x)`, возвращающую вектор `y`, размер которого равен размеру вектора `x` и выполняющую поэлементное вычисление по формуле `y=max(0,x)`.
1. Написать функцию `LinearTransform(M,x,b)`, где `M` - матрица, `x` - вектор, `b` - число. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=M*x+b`, здесь под операцией `*` понимается операция скалярного произведения (dot product) матрицы на вектор.
2. Написать функцию `Transform(M1,M2,x,b1,b2)`, где `M1`,`M2` - матрицы, `x` - вектор, `b1`,`b2` - числа. Функция должна ввозвращать вектор `y`, размер которого равен размеру вектора `x`, где `y` рассчитывается по формуле `y=Function2(LinearTransform(M2,x2,b2))`, а `x2=Function1(LinearTransform(M1,x,b1))`.
3. Задать матрицы M1,M2 размером MxN, вектор размером N, и числа b1,b2 и выполнить вычисления `Transform(M1,M2,x,b1,b2)`, производя замеры времени выполнения функции. **Значения M и N нужно узнать у преподавателя.** 

Все функции задания нужно реализовать с использованием универсальных функций, выполняющих векторизованные операции.

In [149]:
# Выполнение задания
import numpy as np

def Function1(x):
    return 1 / (1 + np.exp(-x))

def Function2(x):
    return np.maximum(0, x)

def LinearTransform(M, x, b):
    return np.dot(M, x) + b

def Transform(M1, M2, x, b1, b2):
    x2 = Function1(LinearTransform(M1, x, b1))
    return Function2(LinearTransform(M2, x2, b2))

M = 60
N = 60
M1 = np.ones((M, N))
M2 = np.ones((M, N))
x = np.ones(N)
b1 = 0.5
b2 = 1.0

y = Transform(M1, M2, x, b1, b2)
print("Результат:", y, '\n')

%timeit y = Transform(M1, M2, x, b1, b2)

Результат: [61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61.
 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61.
 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61. 61.
 61. 61. 61. 61. 61. 61.] 

21.7 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
